name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CI sanity check
        run: |
          echo "✅ CI is working for $GITHUB_REPOSITORY"
          echo "Folder contents:"
          ls -la
